"""Snakemake file defining the workflows"""

################################################################################
# Define Environment
WORKDIR = "../data"


################################################################################
# Imports Utilities
include: "tree_inference.smk"
include: "analyze.smk"
include: "visualize.smk"
# Import Experiments
include: "mark00.smk"
################################################################################

